### ISSUE TITLE
num.adarry object has no attribute 'properties'

### ISSUE THREAD

**Issue by khaitha** [DeepTrackAI/DeepTrack2#218]
I wanted to try on a .jpg. 
`training_image = dt.LoadImage("train\\B1_1_Image001_ICC_rotate.jpg")() /256
plt.imshow(training_image)
plt.axis("off")`

But when i run:
model = dt.models.LodeSTAR(input_shape=(None,None,1))

train_set = (
    dt.Value(training_image)
)

model.fit(
    train_set,
    epoch = 10,
    batch_size = 8
)

I get this error:
/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Exception in thread Thread-13 (_continuous_get_training_data):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deeptrack/generators.py", line 388, in _continuous_get_training_data
    datapoint = self.construct_datapoint(new_image)
  File "/usr/local/lib/python3.10/dist-packages/deeptrack/models/lodestar/generators.py", line 60, in construct_datapoint
    *[
  File "/usr/local/lib/python3.10/dist-packages/deeptrack/models/lodestar/generators.py", line 61, in <listcomp>
    (*self.transformation_function.update().resolve(sample),)
  File "/usr/local/lib/python3.10/dist-packages/deeptrack/features.py", line 192, in __call__
    output = super(Feature, self).__call__(_ID=_ID)
  File "/usr/local/lib/python3.10/dist-packages/deeptrack/backend/core.py", line 307, in __call__
    new_value = self.action(_ID=_ID)
  File "/usr/local/lib/python3.10/dist-packages/deeptrack/features.py", line 315, in action
    new_list = self._process_and_get(image_list, **feature_input)
  File "/usr/local/lib/python3.10/dist-packages/deeptrack/features.py", line 682, in _no_wrap_process_and_get
    new_list = self.get(image_list, **feature_input)
  File "/usr/local/lib/python3.10/dist-packages/deeptrack/features.py", line 775, in get
    image = self.feature_1(image, _ID=_ID)
  File "/usr/local/lib/python3.10/dist-packages/deeptrack/features.py", line 192, in __call__
    output = super(Feature, self).__call__(_ID=_ID)
  File "/usr/local/lib/python3.10/dist-packages/deeptrack/backend/core.py", line 307, in __call__
    new_value = self.action(_ID=_ID)
  File "/usr/local/lib/python3.10/dist-packages/deeptrack/features.py", line 315, in action
    new_list = self._process_and_get(image_list, **feature_input)
  File "/usr/local/lib/python3.10/dist-packages/deeptrack/features.py", line 682, in _no_wrap_process_and_get
    new_list = self.get(image_list, **feature_input)
  File "/usr/local/lib/python3.10/dist-packages/deeptrack/features.py", line 775, in get
    image = self.feature_1(image, _ID=_ID)
  File "/usr/local/lib/python3.10/dist-packages/deeptrack/features.py", line 192, in __call__
    output = super(Feature, self).__call__(_ID=_ID)
  File "/usr/local/lib/python3.10/dist-packages/deeptrack/backend/core.py", line 307, in __call__
    new_value = self.action(_ID=_ID)
  File "/usr/local/lib/python3.10/dist-packages/deeptrack/features.py", line 315, in action
    new_list = self._process_and_get(image_list, **feature_input)
  File "/usr/local/lib/python3.10/dist-packages/deeptrack/augmentations.py", line 85, in _no_wrap_process_and_get
    augmented_image = self.get(image, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deeptrack/augmentations.py", line 430, in get
    for prop in image.properties:
AttributeError: 'numpy.ndarray' object has no attribute 'properties'

**Comment by adrishasarkar** [comment]
Any update here?

**Comment by dimitar10** [comment]
@khaitha are you able to run the example `04. unsupervised_object_detection_with_lodestar` ? Double check with that notebook how the training pipeline and datasets are defined and used. `model.fit` requires `Chain` type as first arg and you are passing `Value` type. Also, try to remove the last bracket `training_image = dt.LoadImage("train\\B1_1_Image001_ICC_rotate.jpg")()` -> `training_image = dt.LoadImage("train\\B1_1_Image001_ICC_rotate.jpg")` to see whether this fixes the problem.

Hope this helps.

**Comment by shuyiloe** [comment]
I downloaded the source code of all the tutorials, then opened it with my jupyter lab and ran it. It appeared that all the image created has the same problem when trying to acquire its properties——**numpy.ndadarry object has no attribute 'properties'**. No matter how i tried, it just did not work and reported the same issue——run on different environment (tensorflow2.18- python3.12-env and pytorch2.5- python3.10-env), run on native windows or Ubuntu, run on colab or jupyterlab or colab(When running in colab, it reports another problem: "ImportError: deeptrack attempted to use a functionality that requires module deeptrack.deeplay, but it couldn't be loaded. Please install deeptrack and retry" ). It nearly drove me crazy and waste a lot my time and energy. I am writting this comment because your project can help me solve a thorny problem and really could boost my research(of course, providing it works) I would appreciate that if you can help me with that! I sincerely would like to commute with  the developer and solve the problem I encounter. Here is my emial: shuyiloe@gmial.com
![图片9](https://github.com/user-attachments/assets/3da177b1-c96d-4906-a8e0-38c874ede7e5)
